# Generated by Django 3.2.12 on 2022-04-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('active', models.IntegerField()),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=32, null=True)),
                ('tel', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.IntegerField()),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliveryStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('active', models.IntegerField()),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'delivery_staff',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('district', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('tel', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('active', models.IntegerField()),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
            options={
                'db_table': 'product_type',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.restaurant'),
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_date', models.CharField(max_length=32)),
                ('delivered_time', models.CharField(max_length=8)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customer')),
                ('delivery_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.deliverystaff')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.restaurant')),
            ],
            options={
                'db_table': 'order_master',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.IntegerField()),
                ('create_time', models.CharField(blank=True, max_length=32, null=True)),
                ('update_time', models.CharField(blank=True, max_length=32, null=True)),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ordermaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producttype')),
            ],
            options={
                'db_table': 'order_detail',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
    ]
