# Generated by Django 3.2.12 on 2022-04-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
